apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "django-api.fullname" . }}-pre-install"
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  containers:
    restartPolicy: OnFailure
      containers:
        - name: django-app
          command: ['/bin/sh', '-c']
          args: >-
          python3 app/manage.py migrate
          
