version: "3.8"

services: 
  app: 
    build: .
    volumes: 
      - .:/app/
    expose:
      - 8000
    ports:
      - "8000:8000"
    container_name: app
    command: ["python3", "app/manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

  db: 
    image: mysql:5.7
    volumes:
        - ./data/mysql/db:/var/lib/mysql
    ports: 
        - "3306:3306" 
    environment:
      MYSQL_DATABASE: 'employees'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    container_name: db

