# Generated by Django 4.1 on 2022-08-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='DateOfJoinging',
            new_name='DateOfJoining',
        ),
    ]
